# Generated by Django 3.2.5 on 2021-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_link',
            field=models.URLField(blank=True),
        ),
    ]
