# Generated by Django 3.2.5 on 2021-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210708_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_safe',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='url_safe',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
