# Generated by Django 3.2.5 on 2021-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
